// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://taveatlaflilwuneyvun.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhdmVhdGxhZmxpbHd1bmV5dnVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwMzQyMTIsImV4cCI6MjA2MjYxMDIxMn0.U7FiUF3oVSkfNgqEwIGyLdVQ6Yez37Ep2b9N3VpIQvs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);